receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  debug:
    verbosity: basic
  prometheus:
    endpoint: 0.0.0.0:8889
  otlphttp/aquila:
    endpoint: http://api:8080
    headers:
      X-Aquila-Ingest-Token: aquila-local-ingest
    tls:
      insecure: true
    compression: none

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/aquila]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
